Fix alembic migrations with SQLAlchemy 2.x
Following the bump of SQLAlchemy to 2.x [1], Blazar devstack jobs
started to fail with the error:

    TypeError: Additional arguments should be named <dialectname>_<argument>, got 'autoload'

Replace autoload=True with autoload_with=engine as documented in the
SQLAlchemy 2.0 migration guide [2].

[1] https://review.opendev.org/c/openstack/requirements/+/879743
[2] https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed

Change-Id: I37f0e70e6ac1898e02546709b6ba197fdad313c0