Fix errors when accessing floating IP API methods
Commit 520005b13dc47bf78db33a526c1947e4b2c0d681 which recently added
microversion support did not update floating IP code to account for the
extra parameter passed to all API methods. This resulted in errors like:

    File "/opt/stack/blazar/blazar/api/v1/utils.py", line 90, in handler
    return func(flask.request, **kwargs)
    TypeError: floatingips_list() takes no arguments (1 given)

Change-Id: I6820b56d0389ec285789ba38a8f82eac93595afc